Definición de milestones
harvestcore/tfm-doc pull request #3
Opened 2022-04-03 17:57 UTC by harvestcore

Este PR resuelve los diversos problemas de definición de los milestones.

La issue fue creada inicialmente [aquí](https://github.com/harvestcore/matroos/issues/24), pero prefiero resolverla antes en este repo de documentación antes que hacer los cambios en los milestones del repo de código. (Por eso los milestones en ese repo no han cambiado aún).

Qué incluye:
- División del milestone 1 en tres milestones distintos, ya que el inicial era demasiado extenso. Se ha separado en:
  - Integración con la base de datos.
  - Creación de bots y configuración de estos.
  - Creación de comandos y configuración de estos.
- Aclaraciones varias en los otros milestones.

2022-04-03 18:01 UTC, harvestcore commented
@jj No puedo añadirte como revisor, pero me gustaría que le echaras un ojo.

2022-04-04 11:32 UTC, JJ commented
Recuerda que los PR también tienen que estar en un milestone.

2022-04-04 11:40 UTC, JJ requested changes
Hay dos objetivos principales en la organización de un proyecto en milestones
1. Ordenar el desarrollo en diferentes etapas, de forma que antes de pasar de una etapa a la siguiente se hayan resuelto todos los escollos en la anterior.
2. Organizar el desarrollo *de cara al público*, organizándolo en hitos internos y externos, los primeros precediendo a los otros. Al final, los hitos externos tienen que cubrir en todo o en parte las historias de usuario.

En general, tienes que replantearte los hitos siguiendo los ejes anteriores. No es necesario que plantees todos los hitos desde el principio. En general, sólo hace falta plantearse el hito en el que está uno trabajando. Si ves complicado planificarlo hasta el final, simplemente crea el hito 0 y el uno (porque el 0 no es código) y sobre la marcha vas decidiendo los siguientes.

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +## 01 - Integración con la base de datos
Recuerda describir como un MVP, no como una tarea. No se trata de que haya que "integrar", se trata de que el producto mínimamente viable incluya integración con la base de datos (u otra fuente de datos)

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +La finalidad de este *milestone* es la creación y configuración de bots. Para ello se ampliará la funcionalidad del proyecto de recursos compartidos ([`resources`](https://github.com/harvestcore/matr
La finalidad de un milestone *siempre* es presentar un producto. Si no describes qué es lo que va a crear y configurar bots, y qué funcionalidad se le añade al anterior y demás, no es un milestone.

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +## 03 - Creación y configuración de comandos
Una vez más, tiene que ser un producto.

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +El objetivo de este *milestone* es la creación y configuración de comandos, los cuales podrán ser configurados en bots para después ser utilizados en los servidores de Discord. Para ello se ampliará
¿Quién o qué va a crear y configurar comandos? ¿Qué quieres decir con "configurar"?

La descripción tiene que ser también bastante precisa.

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +Tras la posibilidad de crear, configurar y almacenar bots, estos se deben poder desplegar. El objetivo de este *milestone* es permitir el despliegue (la ejecución) de los bots en los workers. Esto si
Para empezar, debes hablar de "aplicación desplegada", no que se va a hacer el despliegue.
Para seguir, el despliegue implica muchas fases diferentes, incluyendo tests a todos los niveles. Los tests deben formar parte de la viabilidad de diferentes PMVs que vayas haciendo a lo largo del desarrollo. 
Además, si es un despliegue sería de cara al público (el resto, internos)

2022-04-04 11:40 UTC, JJ commented on md/planificacion/milestones.md
> +## [05 - API REST](https://github.com/harvestcore/matroos/milestone/7)
¿Cómo vas a hacer el despliegue sin API REST? ¿De qué sirve el despliegue si no tienes ese API?

2022-04-07 09:45 UTC, harvestcore commented on md/planificacion/milestones.md
> +## [05 - API REST](https://github.com/harvestcore/matroos/milestone/7)
Quizá no está expresado de la mejor manera. Con desplegar bots en workers me refiero a ejecutar los bots en los workers.

Los milestones 1 a 4 los había pensado para montar toda la infraestructura:

1. Integración con BD (necesario para bots y comandos)
2. Creación y configuración de bots (crear y almacenar bots en BD, poder configurarles comandos)
3. Creación y configuración de comandos (crear y almacenar comandos en BD)
4. Despliegue de los bots en workers (ejecutar los bots en los workers, siendo un worker otro microservicio)

Una vez llegados a ese punto (donde se podrían lanzar bots usando código), comenzaría el milestone 5, en el que se "abre" el software al público con la API Rest.

Por tanto, hasta el M4 (inclusive) se podrían crear comandos, bots y se podrían lanzar bots en workers, pero usando código. Es en el M5 cuando se crearían los endpoints para poder hacer todas esas tareas haciendo uso de la API.

Una vez un usuario se puede comunicar con el sistema mediante la API, entonces ya sí tiene sentido desplegar el software completo (backend, db, workers) en algún servicio cloud o donde sea.

![milestones](https://user-images.githubusercontent.com/22531231/162170878-f4269b2b-e9d4-4c28-ae11-a882cb3ad987.png)

2022-04-07 09:49 UTC, harvestcore commented on md/planificacion/milestones.md
> +Tras la posibilidad de crear, configurar y almacenar bots, estos se deben poder desplegar. El objetivo de este *milestone* es permitir el despliegue (la ejecución) de los bots en los workers. Esto si
En este caso me refiero a la ejecución de los bots en workers. Quizá `despliegue` no es la mejor palabra en ese caso. Como explico en [este comentario](https://github.com/harvestcore/tfm-doc/pull/3#discussion_r844936795), el despliegue "global" del software se encuentra en milestones posteriores. Hasta el hito 5 el software no estaría "público" mediante una API.

2022-04-07 09:57 UTC, harvestcore commented on md/planificacion/milestones.md
> +El objetivo de este *milestone* es la creación y configuración de comandos, los cuales podrán ser configurados en bots para después ser utilizados en los servidores de Discord. Para ello se ampliará
Tomo nota, voy a intentar clarificarlo lo máximo posible.

Los bots y comandos los va a crear un administrador, que (idealmente) tendría conocimientos algo avanzados en administración de sistemas. [Aquí](https://github.com/harvestcore/tfm-doc/blob/develop/md/introduccion/introduccion.md) hay mas info del usuario al que se dirige el software.

Configurar un bot y un comando es similar en ambos casos:
- **Bot**: Una vez se ha creado un bot (se ha aportado una Key que permite la comunicación con Discord, se ha elegido un nombre para ese bot y algún dato extra), éste no tiene ningún comando asociado, por lo que es un bot que no hace nada. Configurar este bot sería, por un lado poder modificar sus parámetros básicos y por otro asociarle comandos para que los pueda ejecutar.
- **Comando**: Una vez se ha creado el comando (aportando datos básicos), es necesario aportar datos extra, como por ejemplo los argumentos que tiene ese comando, o el qué va a hacer ese comando. Más info [aquí](https://github.com/harvestcore/tfm-doc/blob/develop/md/dise%C3%B1o/comandos.md).

2022-04-10 16:17 UTC, harvestcore commented
He actualizado la definición de todos los milestones, @JJ échale un ojo cuando puedas. Gracias.

2022-04-18 20:22 UTC, merged

2022-04-18 20:23 UTC, harvestcore commented
Mezco el PR para seguir con el desarrollo. Si surge alguna duda/discusión lo vemos en otra issue.

2022-04-20 15:55 UTC, JJ commented on md/planificacion/milestones.md
> +## [05 - API REST](https://github.com/harvestcore/matroos/milestone/7)
Ya te lo he puesto en varios sitios, pero insisto aquí. En el propio dibujo se ve que no estás entendiendo el concepto de milestone. Cada milestone es un producto mínimamente viable que abarca a los anteriores; por eso se llaman milestones, porque son diferentes etapas en el desarrollo. Si la integración en bases de datos es el primer milestone, es que no estás organizando bien el desarrollo porque primero se organizan las estructuras de datos y la lógica de negocio.
Pero lo más importante es que no puedes empezar a desarrollar, y avanzar tanto, sin tener historias de usuario reales.
Por favor, párate un momenot y organiza un poco el desarrollo para que pueda continuar correctamente.

2022-04-20 15:58 UTC, JJ reviewed
Lo más importante, apreciaría que esperaras un poco a que yo apruebe un PR antes de fusionarlo. Si me retraso un poco, dame un toque. Pero tienes varios PRs fusionados sin que yo los haya aprobado y, lo que es más, sin que hayas hecho los cambios solicitados.

2022-04-20 15:58 UTC, JJ commented on md/planificacion/milestones.md
> +Este *milestone* incluye la integración del componente principal del software ([`backend`](https://github.com/harvestcore/matroos/tree/develop/backend)) con base de datos (MongoDB) mediante la implem
¿Cómo va a incluir el backend si en el milestone 0 sólo has hecho la infraestructura?

2022-04-20 15:58 UTC, JJ commented on md/planificacion/milestones.md
> +## [02 - Gestión de bots](https://github.com/harvestcore/matroos/milestone/6)
Ya te lo he puesto en otro lugar. Esto no es un milestone. El orden no es el correcto. Y no puedes crear tantos milestones.

2022-04-21 08:54 UTC, harvestcore commented on md/planificacion/milestones.md
> +Este *milestone* incluye la integración del componente principal del software ([`backend`](https://github.com/harvestcore/matroos/tree/develop/backend)) con base de datos (MongoDB) mediante la implem
Se refiere a que ese proyecto (creado de forma básica en el M0) es el que incluye esa nueva funcionalidad.

2022-04-21 08:56 UTC, JJ commented on md/planificacion/milestones.md
> +Este *milestone* incluye la integración del componente principal del software ([`backend`](https://github.com/harvestcore/matroos/tree/develop/backend)) con base de datos (MongoDB) mediante la implem
No, me refiero a que cada milestone es un producto mínimamente viable que se construye sobre el anterior. El 0 no incluye un backend, y en el 1 dices que va a integrar la base de datos con el backend (que no has hecho anteriormente)