Definición de milestones e historias de usuario
harvestcore/tfm-doc pull request #7
Opened 2022-04-24 12:52 UTC by harvestcore

Este PR resuelve los diversos problemas de definición de los milestones y de las historias de usuario.

La issue ha sido creada aquí:  https://github.com/harvestcore/matroos/issues/35, pero se incluye en este repositorio que es el que incluye toda la documentación del proyecto (no del software).

Los milestones y las historias de usuario del repo del software no están actualizadas aún, hasta que el contenido de este PR esté aceptado.

El PR incluye:

- Clarificación de las historias de usuario.
- Reorganización temporal de los milestones.

2022-04-24 12:53 UTC, harvestcore commented
@jj Échale un ojo cuando puedas, gracias. (No puedo agregarte como reviewer)

2022-04-25 12:39 UTC, JJ requested changes
Creo que sería mejor que te concentraras en los primeros pasos, así como en clarificar las HU siguiendo las mejores prácticas que he comentado aquí y en el grupo de Telegram para TFs.

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Resumen                | Como usuario administrador quiero crear distintos bots de Discord en el sistema para poder configurarlos con los comandos que yo quiera para que éstos realicen las tareas q
¿Qué beneficio vas a obtener con los "diferentes" bots? ¿Es beneficioso porque son diferentes? ¿Es beneficioso porque antes no podías y ahora se puede? En general, cada HU tiene que exponer claramente cuál es el problema que se va a resolver y qué beneficio va a obtener el usuario tras la resolución del problema por medios informáticos.

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Meta                   | Creación de bots para que más tarde puedan ser configurados y desplegados y para que puedan ejecutar los comandos configurados en ellos. |
¿Qué beneficio se va a obtener ejecutando los comandos?

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Perfil de usuario      | Usuario administrador con conocimientos avanzados en:<br />- Configuración de Discord.<br />- Administración de sistemas.<br />- Despliegue de software y sistemas. |
Ese usuario administrador, ¿qué no podía hacer antes y qué puede hacer ahora? ¿No podía crear bots? ¿No podía ejecutar comandos?

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Notas funcionales      | - No se debe permitir la creación de bots con el mismo nombre.<br />- No se debe permitir la creación de bots con la misma *key*. |
Esto debería ser un issue a solucionar. Y debe proponerse como un problema. ¿Qué pasa si borramos un bot? ¿Podemos reutilizar la key?

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Resumen                | Como usuario administrador quiero consultar los detalles de los bots de Discord creados en el sistema, para poder ver sus características y su configuración. |
¿Qué beneficio obtienes viendo sus características? ¿O es simplemente una utilidad que permite avanzar hacia otro beneficio contenido en otra historia de usuario?

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Meta                   | Obtener todos los datos de un bot en concreto o de todos los bots creados en el sistema para consultar sus características y configuración. |
¿Qué problema se soluciona con esto?

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Perfil de usuario      | Usuario administrador con conocimientos avanzados en:<br />- Configuración de Discord.<br />- Administración de sistemas.<br />- Despliegue de software y sistemas. |
Si es el mismo que antes, no repitas. Simplemente pon los diferentes usuarios (*personas*) en otro apartado.

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +### 04 - Eliminar un bot
Como issue, no creo que haga falta poner tanto material. Es simplemente un issue que el desarrollador debe permitir (si la HU lo pide, claro)

2022-04-25 12:39 UTC, JJ commented on md/analisis/analisis.md
> +| Notas técnicas         | Elementos necesarios para la creación del comando:<br />- *name: str [req]*. Nombre del comando.<br />- *prefix: str [req]*. Prefijo del comando. |
¿Lo que hace el comando no hay que incluirlo?

2022-04-25 12:39 UTC, JJ commented on md/planificacion/milestones.md
> +### [01 - Gestión de comandos](https://github.com/harvestcore/matroos/milestone/10)
Antes de esto tienes que tener un modelo interno de datos creado por domain driven design. No puedes lanzarte a hacer PMVs concretos sin tener antes ese modelo de capas claro, que permita representar bien el dominio dle problema. Esto lo he repetido varias veces en el grupo de Telegram.

2022-04-25 12:39 UTC, JJ commented on md/planificacion/milestones.md
> +- El [`backend`](https://github.com/harvestcore/matroos/tree/develop/backend) cuenta con un servicio capaz de gestionar los comandos y su configuración.
Pero ¿qué backend? Si esto es el primer milestone. En los primeros milestones tenemos que trabajar a un nivel totalmente abstracto, sin ningún tipo de referencia a arquitecturas específicas.

2022-04-29 10:56 UTC, JJ commented on md/analisis/analisis.md
> +| Meta                   | Creación de bots para que más tarde puedan ser configurados y desplegados y para que puedan ejecutar los comandos configurados en ellos. |
¿Has respondido a estas objeciones?

2022-04-29 11:09 UTC, harvestcore commented on md/analisis/analisis.md
> +| Meta                   | Creación de bots para que más tarde puedan ser configurados y desplegados y para que puedan ejecutar los comandos configurados en ellos. |
> ¿Has respondido a estas objeciones?

Estoy trabajando en este PR ahora mismo, subiré cambios (y responderé a tus comentarios) hoy/esta tarde/asap.

2022-04-30 14:28 UTC, harvestcore commented on md/analisis/analisis.md
> +| Resumen                | Como usuario administrador quiero crear distintos bots de Discord en el sistema para poder configurarlos con los comandos que yo quiera para que éstos realicen las tareas q
Sí, justo eso. El beneficio en esta HU es que poder crear distintos bots permite que cada uno de estos bots pueda tener una funcionalidad y configuración específica, en lugar de tener un bot único con toda la funcionalidad.

2022-04-30 16:28 UTC, JJ commented on md/analisis/analisis.md
> +| Resumen                | Como usuario administrador quiero crear distintos bots de Discord en el sistema para poder configurarlos con los comandos que yo quiera para que éstos realicen las tareas q
Haz énfasis entonces en el beneficio que se va a obtener, y siempre dentro del dominio del problema (que tiene que estar claramente definido)

2022-05-02 12:15 UTC, harvestcore commented on md/analisis/analisis.md
> +| Perfil de usuario      | Usuario administrador con conocimientos avanzados en:<br />- Configuración de Discord.<br />- Administración de sistemas.<br />- Despliegue de software y sistemas. |
Se ha clarificado esto incluyendo más contexto en la introducción al problema y agregando beneficio.

2022-05-02 12:17 UTC, harvestcore commented on md/analisis/analisis.md
> +| Notas funcionales      | - No se debe permitir la creación de bots con el mismo nombre.<br />- No se debe permitir la creación de bots con la misma *key*. |
Claro, en el momento de trabajar en esa HU se crearán las issues necesarias para completarla. En ese caso, si se borra un bot se "pierde" su información, por lo que se podría reutilizar la key.

2022-05-02 12:20 UTC, harvestcore commented on md/analisis/analisis.md
> +| Resumen                | Como usuario administrador quiero consultar los detalles de los bots de Discord creados en el sistema, para poder ver sus características y su configuración. |
El beneficio es ese, ver sus características. E.g.: Un usuario ha creado 50 comandos distintos y quiere saber qué hace uno de ellos en concreto.

2022-05-02 12:21 UTC, harvestcore commented on md/analisis/analisis.md
> +| Meta                   | Obtener todos los datos de un bot en concreto o de todos los bots creados en el sistema para consultar sus características y configuración. |
En el caso de tener distintos bots en activo, saber qué configuración tiene cada uno de ellos (e.g.: qué comandos tiene cada bot)

2022-05-02 12:24 UTC, harvestcore commented on md/analisis/analisis.md
> +| Notas técnicas         | Elementos necesarios para la creación del comando:<br />- *name: str [req]*. Nombre del comando.<br />- *prefix: str [req]*. Prefijo del comando. |
Cómo funcionan los comandos está detallado [aquí](https://github.com/harvestcore/tfm-doc/blob/develop/md/dise%C3%B1o/comandos.md), y es una funcionalidad "estática". En el momento de crear un comando sólo es necesario saber los datos básicos + los específicos de cada tipo de comando.

2022-05-02 15:53 UTC, harvestcore commented on md/planificacion/milestones.md
> +- El [`backend`](https://github.com/harvestcore/matroos/tree/develop/backend) cuenta con un servicio capaz de gestionar los comandos y su configuración.
Agregado milestone (previo a este) para el modelado de datos y lógica de negocio.

2022-05-08 16:32 UTC, JJ approved these changes
Tenía un montón de comentarios pendientes de enviar, lo siento... pensaba que lo había hecho. Por no bloquearte más, pongo aprobación.

2022-05-08 16:32 UTC, JJ commented on md/estado-del-arte/estado-del-arte.md
> +## Aplicaciones similares
Todo esto supongo que lo pasarás, con más rollo, al informe. Es esencial que caracterices claramente de qué estás haciendo el estado del arte y a santo de qué mencionas las cosas que mencionas.

2022-05-08 16:32 UTC, JJ commented on md/estado-del-arte/estado-del-arte.md
> +- [Slack](https://slack.com/)
mattermost es libre, y es un clon de Slack.

2022-05-08 16:32 UTC, JJ commented on md/estado-del-arte/estado-del-arte.md
> +### [Autocode](https://autocode.com/)
Antes de esto, sería mejor que definieras una serie de parámetros o características y lo pusieras en una tabla, para que se pueda hacer una comparación clara. Si con esto es lo que vas a "competir", es esencial.

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +[Discord]([https://discord.com) es una aplicación de mensajería de uso tanto personal como en empresas. Es semejante a otras herramientas que se usan en ámbitos similares, como [Slack](https://slack.
Como te he dicho otras veces, salvo que entender Discord o su arquitectura sea imprescindible para entender tu trabajo, yo lo dejaría todo un poco genérico. Aparte, estás mencionando lo mismo que arriba aquí.

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +- Chat de voz.
¿Todo esto sirve la historia de usuario que incluye al tribunal? ¿No? Pues no lo pongas. ¿Qué quiere el tribunal del informe? ¿Esto lo cumple? Si no, no lo incluyas.

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +En concreto, este proyecto se centra en los bots, que podrían definirse como herramientas que, haciendo uso de diferentes permisos, ayudan a automatizar tareas dentro de un servidor de Discord. Las f
Los bots pueden automatizar cualquier tarea en cualquier sistema de mensajería que lo permita. Lo que tienes que pensar es qué hace a Discord exclusivo, o a tu sistema exclusivo para Discord. 
La cuestión es que tienes que abstraer bien la estructura de un bot para implementar esto. Creo que te estás centrando demasiado en lo accesorio, y no en lo importante: qué partes tiene un bot, cómo almacena el estado. Cómo interaccione con el sistema debería ser accesorio

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +- Usar bots ya existentes. En este caso el procedimiento es similar a Telegram u otras aplicaciones. El bot ya se encuentra creado, configurado y desplegado, y solo es necesario agregarlo al servidor
Si es similar a Telegram, igual podrían servir también para Telegram. En todo caso, no tengo muy claro que esto corresponda aquí. Cuando hables d eimplementación, en un milestone lejano, y de despliegue, entonces es donde tendrás que exponer esto y poner las consideraciones correspondientes.

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +Incidiendo en éste aspecto de forma más técnica, actualmente hay tres maneras de usar bots en Discord.
Estás hablando aquí de cómo se usaría... No tengo muy claro qué, cuando en la introducción lo primero que tendrías que hacer es enunciar el problema y para quién lo vas a solucionar. Eso no lo veo aquí, aunque igual está en algo ya aprobado.

2022-05-08 16:32 UTC, JJ commented on md/introduccion/introduccion.md
> +- Crear un bot a bajo nivel. En este caso el bot se crea haciendo uso de las diferentes APIs que ofrece Discord para ello y la personalización es máxima. En cambio, es más tedioso, y requiere conocim
Como te digo, esto son detalles de implementación que no tienen mucho sentido en este punto.

2022-05-08 16:32 UTC, JJ commented on md/planificacion/milestones.md
> +- Los proyectos necesarios (`recursos`, `backend` y `worker`) están creados y listos para continuar con el desarrollo de nuevas funcionalidades.
Uf, tres proyectos... Yo no descendería a ese detalle. ¿Qué pasa si al final en vez de recursos se llama "assets"? ¿O simplemente decides que eso va a otro milestone?

2022-05-08 16:32 UTC, JJ commented on md/planificacion/milestones.md
> +- La documentación relacionada con el milestone está actualizada y disponible.
La documentación en este punto, quieres decir.

2022-05-08 16:32 UTC, JJ commented on md/planificacion/milestones.md
> +- Los datos necesarios están modelados.
El dominio del problema, no los datos.

2022-05-09 08:54 UTC, harvestcore commented
Mezclo el PR. El paso de la documentación al otro repo se hará progresivamente cerrando los issues correspondientes.

2022-05-09 08:55 UTC, merged